const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const { runPatcher } = require('./heal-patcher');

const AUDIT_FILE = path.resolve(__dirname, '../test-results/healing-audit.json');
const ROOT_DIR = path.resolve(__dirname, '../..');

function exec(cmd, options = {}) {
  return execSync(cmd, { cwd: ROOT_DIR, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'], ...options });
}

function safeExec(cmd, options = {}) {
  try {
    return exec(cmd, options).trim();
  } catch (err) {
    return null;
  }
}

function parseArgs() {
  const args = process.argv.slice(2);
  const options = {
    dryRun: args.includes('--dry-run'),
    noPush: args.includes('--no-push'),
    force: args.includes('--force'),
    base: 'main',
    branch: null,
  };

  const baseIdx = args.indexOf('--base');
  if (baseIdx !== -1 && args[baseIdx + 1]) {
    options.base = args[baseIdx + 1];
  }

  const branchIdx = args.indexOf('--branch');
  if (branchIdx !== -1 && args[branchIdx + 1]) {
    options.branch = args[branchIdx + 1];
  }

  return options;
}

function getRepoInfo() {
  const remoteUrl = safeExec('git config --get remote.origin.url');
  if (!remoteUrl) return null;

  // Supports HTTPS: https://github.com/owner/repo.git or SSH: git@github.com:owner/repo.git
  const match = remoteUrl.match(/github\.com[/:]([\w.-]+)\/([\w.-]+?)(\.git)?$/);
  if (!match) return null;

  return {
    owner: match[1],
    repo: match[2],
  };
}

function getModifiedPageFiles() {
  const statusOutput = safeExec('git status --porcelain tests/pages');
  if (!statusOutput) return [];

  return statusOutput
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      // Line format: " M tests/pages/LoginPage.ts"
      const parts = line.split(/\s+/);
      return parts.slice(1).join(' ');
    });
}

function buildPrBody(patchedFiles, auditEntries) {
  let table = '';
  if (auditEntries && auditEntries.length > 0) {
    table = [
      '| Element | Deprecated Locator | Healed Replacement | Strategy | Status |',
      '|---|---|---|---|---|',
      ...auditEntries.map(
        (e) =>
          `| **${e.elementName || 'Unknown'}** | \`${e.primaryFailed?.value || 'N/A'}\` | \`${e.healedWith?.value || 'N/A'}\` | \`${e.healedWith?.type || 'fallback'}\` | ✅ Verified |`
      ),
    ].join('\n');
  } else {
    table = '_Patched selectors based on active test run verifications._';
  }

  return `## 🛠️ Autonomous Self-Healing Locator Maintenance

The autonomous self-healing test engine detected stale or deprecated element locators during execution and verified resilient fallback locators against the active application DOM.

### 📋 Summary of Changes
- **Patched Files**:
${patchedFiles.map((f) => `  - \`${f}\``).join('\n')}

### 🔍 Healed Locators Ledger
${table}

### 🚀 Benefits of Merging
- **Zero Latency**: Eliminates fallback locator evaluation latency on subsequent test runs.
- **Resilience**: Protects tests from breaking when DOM structures undergo maintenance.
- **Living Page Objects**: Keeps Page Object Models synchronized with active front-end code.

---
*Automated PR generated by \`self-healing-e2e\` autonomous QA bot (\`npm run heal:pr\` / GitHub Actions).*`;
}

function main() {
  console.log('\n================================================================');
  console.log('🤖  AUTONOMOUS QA: AUTOMATED PULL REQUEST BOT (heal:pr)');
  console.log('================================================================\n');

  const options = parseArgs();

  // Step 1: Read any existing audit entries before running patcher
  let cachedAuditEntries = [];
  if (fs.existsSync(AUDIT_FILE)) {
    try {
      cachedAuditEntries = JSON.parse(fs.readFileSync(AUDIT_FILE, 'utf-8'));
    } catch (_) {}
  }

  // Step 2: Apply patches to Page Objects
  console.log('1️⃣  Executing heal-patcher on Page Objects...');
  const patchResult = runPatcher();

  // Step 3: Check for modified files in tests/pages
  const modifiedFiles = getModifiedPageFiles();

  if (modifiedFiles.length === 0 && !options.force) {
    console.log('✨ No stale selectors detected in Page Objects.');
    console.log('   All Page Object locators are in sync with the active DOM.');
    console.log('   No branch or Pull Request needed.\n');
    return;
  }

  console.log(`\n2️⃣  Detected ${modifiedFiles.length} modified Page Object file(s):`);
  modifiedFiles.forEach((file) => console.log(`   - ${file}`));

  // Generate branch name
  const timestamp = new Date()
    .toISOString()
    .replace(/[:.]/g, '-')
    .slice(0, 19)
    .toLowerCase();
  const branchName = options.branch || `auto-heal/selectors-${timestamp}`;
  const prTitle = 'chore(auto-heal): update stale selectors in Page Objects';
  const prBody = buildPrBody(modifiedFiles, patchResult.auditEntries.length ? patchResult.auditEntries : cachedAuditEntries);

  if (options.dryRun) {
    console.log('\n================== [DRY RUN PREVIEW] ==================');
    console.log(`Target Base Branch : ${options.base}`);
    console.log(`Proposed Branch    : ${branchName}`);
    console.log(`Proposed PR Title  : ${prTitle}`);
    console.log('\n--- PR BODY PREVIEW ---');
    console.log(prBody);
    console.log('=======================================================\n');
    console.log('✅ Dry run completed successfully. No git operations performed.\n');
    return;
  }

  // Step 4: Perform Git Branching & Commit
  const currentBranch = safeExec('git rev-parse --abbrev-ref HEAD') || 'main';
  console.log(`\n3️⃣  Current branch: ${currentBranch}. Creating branch '${branchName}'...`);

  try {
    exec(`git checkout -b ${branchName}`);
    exec('git add tests/pages');

    const commitMsg = `${prTitle}\n\nAutomated fix generated by autonomous self-healing test engine.\nPatched files:\n${modifiedFiles.map((f) => `- ${f}`).join('\n')}`;
    fs.writeFileSync(path.join(ROOT_DIR, '.git', 'COMMIT_EDITMSG_TEMP'), commitMsg, 'utf-8');
    exec(`git commit -F .git/COMMIT_EDITMSG_TEMP`);
    try {
      fs.unlinkSync(path.join(ROOT_DIR, '.git', 'COMMIT_EDITMSG_TEMP'));
    } catch (_) {}

    console.log(`✅ Changes committed to '${branchName}'.`);

    if (options.noPush) {
      console.log(`ℹ️  Skipping remote push (--no-push specified).`);
      exec(`git checkout ${currentBranch}`);
      console.log(`Switched back to '${currentBranch}'.`);
      return;
    }

    // Step 5: Push Branch to Origin
    console.log(`\n4️⃣  Pushing '${branchName}' to origin...`);
    exec(`git push -u origin ${branchName}`);
    console.log(`✅ Successfully pushed '${branchName}' to remote.`);

    // Step 6: Create or output Pull Request URL
    console.log(`\n5️⃣  Resolving Pull Request options...`);
    const repoInfo = getRepoInfo();

    // Check if GitHub CLI is installed and authenticated
    const ghVersion = safeExec('gh --version');
    let ghPrCreated = false;

    if (ghVersion) {
      const ghAuth = safeExec('gh auth status');
      if (ghAuth && !ghAuth.includes('Logged in to') && !ghAuth.includes('github.com')) {
        // gh installed but maybe unauthenticated
      } else {
        console.log('   Found GitHub CLI (`gh`). Attempting automated PR creation...');
        const tempBodyFile = path.join(ROOT_DIR, '.git', 'PR_BODY_TEMP.md');
        fs.writeFileSync(tempBodyFile, prBody, 'utf-8');
        const ghResult = safeExec(`gh pr create --base ${options.base} --head ${branchName} --title "${prTitle}" --body-file "${tempBodyFile}"`);
        try {
          fs.unlinkSync(tempBodyFile);
        } catch (_) {}

        if (ghResult) {
          console.log(`\n🎉 Automated Pull Request Created Successfully!`);
          console.log(`🔗 PR Link: ${ghResult}`);
          ghPrCreated = true;
        }
      }
    }

    if (!ghPrCreated && repoInfo) {
      const compareUrl = `https://github.com/${repoInfo.owner}/${repoInfo.repo}/compare/${options.base}...${branchName}?expand=1`;
      console.log('\n================================================================');
      console.log('🎉  AUTOMATED PULL REQUEST BRANCH READY ON GITHUB');
      console.log('================================================================');
      console.log(`\n🔗 Open this link in your browser to review and merge your PR:`);
      console.log(`   \x1b[36m${compareUrl}\x1b[0m\n`);
      console.log(`Branch Name : ${branchName}`);
      console.log(`Base Branch : ${options.base}`);
      console.log(`PR Title    : ${prTitle}\n`);
    }

    // Switch back to original branch
    exec(`git checkout ${currentBranch}`);
    console.log(`🔄 Switched local branch back to '${currentBranch}'.\n`);
  } catch (err) {
    console.error('\n❌ Error during git/PR automation:', err.message);
    if (err.stdout) console.error(err.stdout);
    if (err.stderr) console.error(err.stderr);

    // Ensure we attempt to switch back to original branch
    try {
      exec(`git checkout ${currentBranch}`);
    } catch (_) {}
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = { main, parseArgs, buildPrBody };
